Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/HandleExceptions:
  AllowComments: true

Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 110
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
